sudo: required
services: 
  - docker

before_install:
  - docker build -t besenti/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true besenti/react-test npm test -- --coverage

after_success:
  - docker build --platform linux/arm64 -t besenti/multi-client ./client
  - docker build --platform linux/arm64 -t besenti/multi-nginx ./nginx
  - docker build --platform linux/arm64 -t besenti/multi-server ./server
  - docker build --platform linux/arm64 -t besenti/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the above images and push them to docker hub
  - docker push besenti/multi-client
  - docker push besenti/multi-nginx
  - docker push besenti/multi-server
  - docker push besenti/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-174764229346'
  bucket_path: 'multi-docker'
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

